#pragma once
#include "hw_def.h"
#include "log.h"
#include "eeprom.h"
#include "qmk/port/platforms/eeprom.h"
void eeconfig_disable(void);
void eeconfig_init(void);
bool eeconfig_init_quantum_checked(void);
void eeconfig_publish_quantum_defaults(void);
