#pragma once

#define G_TERM_ENABLE
#define TAPDANCE_ENABLE
#define TAP_DANCE_ENABLE
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define RETRO_TAPPING_PER_KEY
#define RGBLIGHT_ENABLE
#define RGBLIGHT_SLEEP
