#pragma once

#include <stdbool.h>
#include <stdint.h>


// V260823R2: GET/SET_KEYBOARD_VALUE의 버전형 32바이트 USB 진단 봉투.
#define ERA_USB_DIAGNOSTICS_KEYBOARD_VALUE       0x07U
#define ERA_USB_DIAGNOSTICS_PROTOCOL_VERSION     0x01U
#define ERA_USB_DIAGNOSTICS_PACKET_SIZE          32U
#define ERA_USB_DIAGNOSTICS_PAYLOAD_OFFSET       14U
#define ERA_USB_DIAGNOSTICS_PAYLOAD_SIZE         18U
#define ERA_USB_DIAGNOSTICS_BASE_CHUNKS          8U

#define ERA_USB_DIAGNOSTICS_OP_CAPABILITIES      0x00U
#define ERA_USB_DIAGNOSTICS_OP_SNAPSHOT          0x01U
#define ERA_USB_DIAGNOSTICS_OP_START             0x10U
#define ERA_USB_DIAGNOSTICS_OP_STOP              0x11U
#define ERA_USB_DIAGNOSTICS_OP_CLEAR             0x12U

#define ERA_USB_DIAGNOSTICS_STATUS_OK                  0x00U
#define ERA_USB_DIAGNOSTICS_STATUS_UNSUPPORTED_VERSION 0x01U
#define ERA_USB_DIAGNOSTICS_STATUS_INVALID             0x02U
#define ERA_USB_DIAGNOSTICS_STATUS_BUSY                0x03U
#define ERA_USB_DIAGNOSTICS_STATUS_NO_SESSION          0x04U
#define ERA_USB_DIAGNOSTICS_STATUS_STALE_SNAPSHOT      0x05U

#define ERA_USB_DIAGNOSTICS_CAP_REPORT_TIMING     0x01U
#define ERA_USB_DIAGNOSTICS_CAP_HISTOGRAM         0x02U
#define ERA_USB_DIAGNOSTICS_CAP_FIRMWARE_TIMING   0x04U
#define ERA_USB_DIAGNOSTICS_CAP_EVENT_TIMELINE    0x08U
#define ERA_USB_DIAGNOSTICS_CAP_BOOT_COUNTERS     0x10U


bool era_usb_diagnostics_via_command(uint8_t *data, uint8_t length);
